/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ALLGUI;

import ALLCLASS.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author A7med_Sa3d
 */
public class AddNewArtistFrom extends javax.swing.JFrame {

    /**
     * Creates new form AddNewArtistFrom
     */
    public AddNewArtistFrom() {
        initComponents();
        this.setLocationRelativeTo(null);
        setidlabel.setText("" +(ReadWriteDataFromFiles.pearsonssize + 1) );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formheadertop = new javax.swing.JPanel();
        formheader = new javax.swing.JLabel();
        closebtn = new javax.swing.JLabel();
        minmizbtn = new javax.swing.JLabel();
        formbody = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        youridlabel = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        usernamefield = new javax.swing.JTextField();
        passwordlabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        repasswordlabel = new javax.swing.JLabel();
        rePasswordField = new javax.swing.JPasswordField();
        agelabel = new javax.swing.JLabel();
        agefield = new javax.swing.JTextField();
        nationalitylabel = new javax.swing.JLabel();
        nationalityfield = new javax.swing.JTextField();
        typeofartslabel = new javax.swing.JLabel();
        typeofartsfield = new javax.swing.JTextField();
        registerbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        setidlabel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        formheadertop.setBackground(new java.awt.Color(87, 101, 116));

        formheader.setFont(new java.awt.Font("Algerian", 3, 40)); // NOI18N
        formheader.setForeground(new java.awt.Color(255, 255, 255));
        formheader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formheader.setText("ART GALLERY");

        closebtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        closebtn.setForeground(new java.awt.Color(255, 255, 255));
        closebtn.setText("X");
        closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });

        minmizbtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        minmizbtn.setForeground(new java.awt.Color(255, 255, 255));
        minmizbtn.setText("-");
        minmizbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minmizbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minmizbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout formheadertopLayout = new javax.swing.GroupLayout(formheadertop);
        formheadertop.setLayout(formheadertopLayout);
        formheadertopLayout.setHorizontalGroup(
            formheadertopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formheadertopLayout.createSequentialGroup()
                .addContainerGap(354, Short.MAX_VALUE)
                .addComponent(formheader, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(308, 308, 308)
                .addComponent(minmizbtn)
                .addGap(18, 18, 18)
                .addComponent(closebtn)
                .addGap(20, 20, 20))
        );
        formheadertopLayout.setVerticalGroup(
            formheadertopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formheadertopLayout.createSequentialGroup()
                .addGroup(formheadertopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formheader, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minmizbtn)
                    .addComponent(closebtn))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        formbody.setBackground(new java.awt.Color(34, 47, 62));
        formbody.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(225, 225, 225));

        youridlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        youridlabel.setText("Your ID :");

        namelabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        namelabel.setText("Name :");

        usernamefield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernamefield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernamefieldKeyTyped(evt);
            }
        });

        passwordlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passwordlabel.setText("Password :");

        passwordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        repasswordlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        repasswordlabel.setText("RePassword :");

        rePasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        agelabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        agelabel.setText("Age :");

        agefield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agefield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                agefieldKeyTyped(evt);
            }
        });

        nationalitylabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nationalitylabel.setText("Nationality :");

        nationalityfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nationalityfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nationalityfieldKeyTyped(evt);
            }
        });

        typeofartslabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        typeofartslabel.setText("Art Type :");

        typeofartsfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        typeofartsfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                typeofartsfieldKeyTyped(evt);
            }
        });

        registerbtn.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        registerbtn.setText("Submit");
        registerbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerbtnMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 28)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sign Up");

        setidlabel.setEditable(false);
        setidlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(youridlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(setidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usernamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(passwordlabel)
                        .addGap(20, 20, 20)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(repasswordlabel)
                        .addGap(12, 12, 12)
                        .addComponent(rePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(agelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(agefield, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(typeofartslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(nationalitylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nationalityfield, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeofartsfield, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(youridlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(passwordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(repasswordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(rePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nationalityfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nationalitylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeofartslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeofartsfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registerbtn)
                .addContainerGap())
        );

        formbody.add(jPanel1);
        jPanel1.setBounds(830, 80, 360, 430);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gallery-2931925_1280.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        formbody.add(jLabel1);
        jLabel1.setBounds(0, 0, 1210, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formheadertop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formbody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formheadertop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formbody, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private Boolean checkname()
    {
        for(int i = 0 ; i<ReadWriteDataFromFiles.pearsonssize ; i++)
            if(ReadWriteDataFromFiles.pearsons[i].getName().equals(usernamefield.getText()))
                return false;
         return true;
    }
    
    private Boolean checkdata()
    {
        if(usernamefield.getText().equals("") || agefield.getText().equals("") ||typeofartsfield.getText().equals("")  ||passwordField.getText().equals("") || rePasswordField.getText().equals("") ||agefield.getText().equals(""))
        {
           JOptionPane.showMessageDialog(this,"Empty Fields.","Message", JOptionPane.WARNING_MESSAGE);
            return false; 
        }
        if(!passwordField.getText().equals(rePasswordField.getText()))
        {
           JOptionPane.showMessageDialog(this,"Passwords isn't the same.","Message", JOptionPane.WARNING_MESSAGE);
            return false; 
        }
        if(!checkname())
         {
           JOptionPane.showMessageDialog(this,"This name is used before.\nChange it.","Message", JOptionPane.WARNING_MESSAGE);
            return false; 
        }
        
      return true;
    }
   
    
    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        LOGINFORM xx = new LOGINFORM();
        xx.setVisible(true);
        xx.pack();
        xx.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_closebtnMouseClicked

    private void minmizbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minmizbtnMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minmizbtnMouseClicked

    private void registerbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbtnMouseClicked

        if(checkdata())
        {
            ARTIST artist = new ARTIST();
            artist.setId(ReadWriteDataFromFiles.pearsonssize+1);
            artist.setName(usernamefield.getText());
            artist.setPassword(passwordField.getText());
            artist.setNationality(nationalityfield.getText());
            artist.setAge(Integer.parseInt(agefield.getText()));
            String arr[] = typeofartsfield.getText().split("-");
            artist.setStyleOfArts(arr);
            artist.setnOfStyleOfArts(arr.length);
            
            ReadWriteDataFromFiles.add_artist(artist);
            JOptionPane.showMessageDialog(this,"Data Saved Sir.","Message", JOptionPane.INFORMATION_MESSAGE);
 
            LOGINFORM xx = new LOGINFORM();
            xx.setVisible(true);
            xx.pack();
            xx.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }

    }//GEN-LAST:event_registerbtnMouseClicked

    private void agefieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agefieldKeyTyped
        // TODO add your handling code here:
         if(!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_agefieldKeyTyped

    private void usernamefieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernamefieldKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_usernamefieldKeyTyped

    private void nationalityfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nationalityfieldKeyTyped
        // TODO add your handling code here:
         if(Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_nationalityfieldKeyTyped

    private void typeofartsfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_typeofartsfieldKeyTyped
        // TODO add your handling code here:
         if(Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_typeofartsfieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewArtistFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewArtistFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewArtistFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewArtistFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewArtistFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agefield;
    private javax.swing.JLabel agelabel;
    private javax.swing.JLabel closebtn;
    private javax.swing.JPanel formbody;
    private javax.swing.JLabel formheader;
    private javax.swing.JPanel formheadertop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minmizbtn;
    private javax.swing.JLabel namelabel;
    private javax.swing.JTextField nationalityfield;
    private javax.swing.JLabel nationalitylabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JPasswordField rePasswordField;
    private javax.swing.JButton registerbtn;
    private javax.swing.JLabel repasswordlabel;
    private javax.swing.JTextField setidlabel;
    private javax.swing.JTextField typeofartsfield;
    private javax.swing.JLabel typeofartslabel;
    private javax.swing.JTextField usernamefield;
    private javax.swing.JLabel youridlabel;
    // End of variables declaration//GEN-END:variables
}
