/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ALLGUI;
import ALLCLASS.*;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A7med_Sa3d
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    private int changephoto = 0;
    private String addimagepath;
    public AdminPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        addphotoid1.setText("" + (ReadWriteDataFromFiles.artworksize + 1));
        set_home_data();
        set_customer_tbl();
        set_artist_tbl();
        set_gallary_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        minminze = new javax.swing.JLabel();
        closeicon = new javax.swing.JLabel();
        adminbody = new javax.swing.JTabbedPane();
        hometab = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        totalartsitslabel = new javax.swing.JLabel();
        totalartsitslabel1 = new javax.swing.JLabel();
        totalcustomersslabel2 = new javax.swing.JLabel();
        totalcustomersslabel1 = new javax.swing.JLabel();
        totalartworkslabel2 = new javax.swing.JLabel();
        totalartworkslabel3 = new javax.swing.JLabel();
        totalartboughtphtotolabel4 = new javax.swing.JLabel();
        totalartboughtphtotolabel3 = new javax.swing.JLabel();
        totalearnedmoneylabel5 = new javax.swing.JLabel();
        totalearnedmoneylabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        datatblstab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        artisttbl = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        customertbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        gallaytab = new javax.swing.JPanel();
        photoplacejLabel2 = new javax.swing.JLabel();
        chngenuberlabel = new javax.swing.JLabel();
        nextportfoliojButton1 = new javax.swing.JButton();
        previousportfoliojButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        setidLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        settitleLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        setpriceLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        seyearLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        setcategoryLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        setartistmaderLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        setcustomerboughtrLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        addphototab3 = new javax.swing.JPanel();
        photoplacelabel1 = new javax.swing.JLabel();
        Choose_Photo_jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        idjLabel10 = new javax.swing.JLabel();
        addphotoid1 = new javax.swing.JLabel();
        titlephotojLabel11 = new javax.swing.JLabel();
        titleofphototetxtfield1 = new javax.swing.JTextField();
        yearmadelabel3 = new javax.swing.JLabel();
        yearmadetextfield1 = new javax.swing.JTextField();
        yearmadelabel4 = new javax.swing.JLabel();
        priceindollartextfield1 = new javax.swing.JTextField();
        yearmadelabel5 = new javax.swing.JLabel();
        categorytextfield1 = new javax.swing.JTextField();
        Save__photo_jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Head.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ART GALLERY");

        minminze.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        minminze.setForeground(new java.awt.Color(255, 255, 255));
        minminze.setText("-");
        minminze.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minminze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minminzeMouseClicked(evt);
            }
        });

        closeicon.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        closeicon.setForeground(new java.awt.Color(255, 255, 255));
        closeicon.setText("X");
        closeicon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeiconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeadLayout = new javax.swing.GroupLayout(Head);
        Head.setLayout(HeadLayout);
        HeadLayout.setHorizontalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 394, Short.MAX_VALUE)
                .addComponent(minminze)
                .addGap(18, 18, 18)
                .addComponent(closeicon)
                .addContainerGap())
        );
        HeadLayout.setVerticalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minminze)
                    .addComponent(closeicon))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        adminbody.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        hometab.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 172, 38));

        totalartsitslabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalartsitslabel.setText("Total Artists :");

        totalartsitslabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        totalcustomersslabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalcustomersslabel2.setText("Total Customer :");

        totalcustomersslabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        totalartworkslabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalartworkslabel2.setText("Total artworks :");

        totalartworkslabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        totalartboughtphtotolabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalartboughtphtotolabel4.setText("Total Sold Photos :");

        totalartboughtphtotolabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        totalearnedmoneylabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalearnedmoneylabel5.setText("Total Earned Money :");

        totalearnedmoneylabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("System Information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(totalearnedmoneylabel5)
                        .addGap(27, 27, 27)
                        .addComponent(totalearnedmoneylabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalartboughtphtotolabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalartworkslabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalartworkslabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalartboughtphtotolabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(totalartsitslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(totalartsitslabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(totalcustomersslabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(totalcustomersslabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel12)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalartsitslabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalartsitslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalcustomersslabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalcustomersslabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalartworkslabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalartworkslabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalartboughtphtotolabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalartboughtphtotolabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalearnedmoneylabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalearnedmoneylabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        hometab.add(jPanel1);
        jPanel1.setBounds(760, 70, 370, 390);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pexels-photo-1269968.jpeg"))); // NOI18N
        jLabel11.setText("jLabel11");
        hometab.add(jLabel11);
        jLabel11.setBounds(0, 0, 1220, 600);

        adminbody.addTab("Home", hometab);

        datatblstab.setLayout(null);

        artisttbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "User Name", "Age", "Nationality", "n.Style.Arts", "StyleOfArts", "T.Photos", "T.B.photos", "T.E.Money"
            }
        ));
        jScrollPane1.setViewportView(artisttbl);

        datatblstab.add(jScrollPane1);
        jScrollPane1.setBounds(240, 240, 878, 324);

        customertbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "User Name", "Address", "T. B.Photo", "T.M.Spent"
            }
        ));
        jScrollPane2.setViewportView(customertbl);

        datatblstab.add(jScrollPane2);
        jScrollPane2.setBounds(240, 70, 878, 129);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Artists :");
        datatblstab.add(jLabel2);
        jLabel2.setBounds(30, 380, 168, 34);

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Customers :");
        datatblstab.add(jLabel3);
        jLabel3.setBounds(10, 120, 210, 34);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pexels-photo-1269968.jpeg"))); // NOI18N
        jLabel13.setText("jLabel13");
        datatblstab.add(jLabel13);
        jLabel13.setBounds(0, 0, 1220, 600);

        adminbody.addTab("Data Tbls", datatblstab);

        gallaytab.setLayout(null);
        gallaytab.add(photoplacejLabel2);
        photoplacejLabel2.setBounds(690, 60, 480, 320);
        gallaytab.add(chngenuberlabel);
        chngenuberlabel.setBounds(910, 430, 59, 25);

        nextportfoliojButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nextportfoliojButton1.setText("Next");
        nextportfoliojButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextportfoliojButton1ActionPerformed(evt);
            }
        });
        gallaytab.add(nextportfoliojButton1);
        nextportfoliojButton1.setBounds(1030, 430, 120, 25);

        previousportfoliojButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        previousportfoliojButton2.setText("Previous");
        previousportfoliojButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousportfoliojButton2MouseClicked(evt);
            }
        });
        gallaytab.add(previousportfoliojButton2);
        previousportfoliojButton2.setBounds(730, 430, 120, 25);

        jPanel2.setBackground(new java.awt.Color(255, 172, 38));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Id :");

        setidLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Title :");

        settitleLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Price :");

        setpriceLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Year :");

        seyearLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Category : ");

        setcategoryLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Artist : ");

        setartistmaderLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Customer Bought :");

        setcustomerboughtrLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Sales informations");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(setidLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(setpriceLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(seyearLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(setcategoryLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(setartistmaderLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(setcustomerboughtrLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(settitleLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel14)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(setidLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settitleLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setpriceLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seyearLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setcategoryLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(setartistmaderLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setcustomerboughtrLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        gallaytab.add(jPanel2);
        jPanel2.setBounds(30, 50, 367, 414);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pexels-photo-1269968.jpeg"))); // NOI18N
        jLabel15.setText("jLabel15");
        gallaytab.add(jLabel15);
        jLabel15.setBounds(0, 0, 1220, 600);

        adminbody.addTab("Gallary", gallaytab);

        addphototab3.setLayout(null);

        photoplacelabel1.setBackground(new java.awt.Color(255, 102, 102));
        addphototab3.add(photoplacelabel1);
        photoplacelabel1.setBounds(670, 65, 480, 340);

        Choose_Photo_jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Choose_Photo_jButton3.setText("Choose Photo");
        Choose_Photo_jButton3.setIconTextGap(10);
        Choose_Photo_jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choose_Photo_jButton3ActionPerformed(evt);
            }
        });
        addphototab3.add(Choose_Photo_jButton3);
        Choose_Photo_jButton3.setBounds(860, 470, 233, 40);

        jPanel3.setBackground(new java.awt.Color(255, 172, 38));

        idjLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        idjLabel10.setText("Id :");

        addphotoid1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        titlephotojLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titlephotojLabel11.setText("Title :");

        yearmadelabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        yearmadelabel3.setText("Year : ");

        yearmadetextfield1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearmadetextfield1KeyTyped(evt);
            }
        });

        yearmadelabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        yearmadelabel4.setText("Price :");

        priceindollartextfield1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceindollartextfield1KeyTyped(evt);
            }
        });

        yearmadelabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        yearmadelabel5.setText("Category :");

        Save__photo_jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Save__photo_jButton2.setText("Save");
        Save__photo_jButton2.setIconTextGap(10);
        Save__photo_jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Save__photo_jButton2MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Photo Information");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(yearmadelabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(yearmadelabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(categorytextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(yearmadelabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titlephotojLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(idjLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(addphotoid1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(priceindollartextfield1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(yearmadetextfield1)
                            .addComponent(titleofphototetxtfield1))))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Save__photo_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel16)
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addphotoid1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idjLabel10))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlephotojLabel11)
                    .addComponent(titleofphototetxtfield1))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearmadelabel3)
                    .addComponent(yearmadetextfield1))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearmadelabel4)
                    .addComponent(priceindollartextfield1))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearmadelabel5)
                    .addComponent(categorytextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Save__photo_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        addphototab3.add(jPanel3);
        jPanel3.setBounds(50, 70, 360, 420);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pexels-photo-1269968.jpeg"))); // NOI18N
        jLabel17.setText("jLabel17");
        addphototab3.add(jLabel17);
        jLabel17.setBounds(0, 0, 1220, 600);

        adminbody.addTab("Add Photo", addphototab3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(adminbody)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminbody, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ImageIcon resizeImage(String imagepath , byte[] pic,JLabel x)
    {
        ImageIcon myimg = null;
        if(imagepath !=null)
            myimg = new ImageIcon(imagepath);
        else
            myimg = new ImageIcon(pic);
        Image img = myimg.getImage();
        Image img2 = img.getScaledInstance(x.getWidth(),x.getHeight(),Image.SCALE_SMOOTH);
        
        ImageIcon imageicon = new ImageIcon(img2);
        
    return imageicon;
    }
    
    
    private void minminzeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minminzeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minminzeMouseClicked

    private void closeiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeiconMouseClicked
        //System.exit(0);
        this.dispose();
        new LOGINFORM().setVisible(true);
    }//GEN-LAST:event_closeiconMouseClicked

    private void nextportfoliojButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextportfoliojButton1ActionPerformed
        // TODO add your handling code here:
        if(ReadWriteDataFromFiles.artworksize > 0)
        {
            changephoto++;
            if(changephoto == ReadWriteDataFromFiles.artworksize )
                    changephoto = 0;
            set_gallary_data();
        }
        else
        JOptionPane.showMessageDialog(this,"System havn't any photo.","Message", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_nextportfoliojButton1ActionPerformed

    private void previousportfoliojButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousportfoliojButton2MouseClicked
        // TODO add your handling code here:
        if(ReadWriteDataFromFiles.artworksize > 0)
        {
            changephoto--;
            if(changephoto == -1 )
                changephoto = ReadWriteDataFromFiles.artworksize - 1;
            set_gallary_data();
        }
        else
        JOptionPane.showMessageDialog(this,"System havn't any photo.","Message", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_previousportfoliojButton2MouseClicked

    private void Save__photo_jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Save__photo_jButton2MouseClicked
        // TODO add your handling code here:
        if(check_add_photo_data() && check_add_photo_name(titleofphototetxtfield1.getText()))
        {
            ARTWORK newartwork = new ARTWORK();
            newartwork.setId(ReadWriteDataFromFiles.artworksize+1);
            newartwork.setTitle(titleofphototetxtfield1.getText());
            newartwork.setIdArtist(0);
            newartwork.setIdCustomer(0);
            
            newartwork.setYear(Integer.parseInt(yearmadetextfield1.getText()));
            newartwork.setPrice(Integer.parseInt(priceindollartextfield1.getText()));
            newartwork.setTypeOfArt(categorytextfield1.getText());
            newartwork.setPath(addimagepath);
            
            JOptionPane.showMessageDialog(this,"Data Saved Sir.","Message", JOptionPane.OK_OPTION);
            ReadWriteDataFromFiles.addNewartwork(newartwork);
            ReadWriteDataFromFiles.WriteDataIntoArtWork();
            addphotoid1.setText("" + (ReadWriteDataFromFiles.artworksize+1));
            titleofphototetxtfield1.setText("");
            yearmadetextfield1.setText("");
            priceindollartextfield1.setText("");
            categorytextfield1.setText("");
            addimagepath = "";
            photoplacelabel1.setIcon(null);
           
            set_gallary_data();
            set_home_data();
        }
        
    }//GEN-LAST:event_Save__photo_jButton2MouseClicked

    private void Choose_Photo_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choose_Photo_jButton3ActionPerformed
        // TODO add your handling code here:
         JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images","jpg","png");
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File selectedfile = file.getSelectedFile();
            addimagepath = selectedfile.getAbsolutePath();
            photoplacelabel1.setIcon(resizeImage(addimagepath, null,photoplacelabel1));
        }
        else
        {
            JOptionPane.showMessageDialog(this,"No File Chooser","Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Choose_Photo_jButton3ActionPerformed

    private void yearmadetextfield1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearmadetextfield1KeyTyped
        // TODO add your handling code here:
         if(!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_yearmadetextfield1KeyTyped

    private void priceindollartextfield1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceindollartextfield1KeyTyped
        // TODO add your handling code here:
         if(!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_priceindollartextfield1KeyTyped

    private Boolean check_add_photo_data()
    {
        if(titleofphototetxtfield1.getText().equals("") || yearmadetextfield1.getText().equals("") ||priceindollartextfield1.getText().equals("") ||categorytextfield1.getText().equals("") ||photoplacelabel1.getIcon() == null )
        {
           JOptionPane.showMessageDialog(this,"Empty Fields.","Message", JOptionPane.WARNING_MESSAGE);
            return false; 
        }
        
      return true;
    }
    
    private Boolean check_add_photo_name(String newname)
    {
        for(int i = 0 ;i<ReadWriteDataFromFiles.artworksize ; i++)
            if(ReadWriteDataFromFiles.artwork[i].getTitle().equals(newname))
            {
                JOptionPane.showMessageDialog(this,"this is name is used before.","Message", JOptionPane.ERROR_MESSAGE);
                return false;
            }
    return true;
    }
     
    
    
    private void set_home_data()
    {
        totalartsitslabel1.setText("" + ReadWriteDataFromFiles.artistssize);
        totalcustomersslabel1.setText("" + ReadWriteDataFromFiles.customersize);
        totalartworkslabel3.setText("" + ReadWriteDataFromFiles.artworksize);
        
        int totalboughtphoto = 0 , totalearnedmoney = 0;
        for(int i = 0 ; i<ReadWriteDataFromFiles.artworksize ; i++)
            if(ReadWriteDataFromFiles.artwork[i].getIdCustomer() > 0)
            {
                totalboughtphoto++;
                totalearnedmoney += ReadWriteDataFromFiles.artwork[i].getPrice();
            }
        totalartboughtphtotolabel3.setText("" + totalboughtphoto);
        totalearnedmoneylabel4.setText("" + totalearnedmoney + " $");
    }
    
    private void set_customer_tbl()
    {
        DefaultTableModel tblmodel = (DefaultTableModel)customertbl.getModel();
      
        int totalboughtphoto = 0,totalspentmoney = 0 , thisid;
        
        for(int i = 0 ; i<ReadWriteDataFromFiles.pearsonssize ; i++)
        {
             if(ReadWriteDataFromFiles.pearsons[i] instanceof CUSTOMER )
                {
                    CUSTOMER customer = new CUSTOMER();
                    customer = (CUSTOMER) ReadWriteDataFromFiles.pearsons[i].get_data();
            totalboughtphoto = 0;
            totalspentmoney = 0;
            
            thisid = customer.getId();
            for(int j = 0 ;j<ReadWriteDataFromFiles.artworksize;j++)
                if(ReadWriteDataFromFiles.artwork[j].getIdCustomer() == thisid)
                {
                   totalspentmoney += ReadWriteDataFromFiles.artwork[j].getPrice();
                   totalboughtphoto++;  
                }
                tblmodel.addRow(new Object[]{
               (""+ thisid),customer.getName(),customer.getAddress(),
               (""+totalboughtphoto),(""+totalspentmoney + "$")  });
                }
        }
        
    }
    
    private void set_artist_tbl()
    {
        DefaultTableModel tblmodel = (DefaultTableModel)artisttbl.getModel();
        int totalboughtphoto = 0,totalearnedmoney = 0 ,totalphotos = 0, thisid;
        
        for(int i = 0 ; i<ReadWriteDataFromFiles.pearsonssize ; i++)
        {
            totalboughtphoto = 0;
            totalearnedmoney = 0;
            totalphotos = 0;
           if(ReadWriteDataFromFiles.pearsons[i] instanceof ARTIST)
                {
                    ARTIST artist = new ARTIST();
                    artist = (ARTIST) ReadWriteDataFromFiles.pearsons[i].get_data();
            thisid = artist.getId();
            for(int j = 0 ;j<ReadWriteDataFromFiles.artworksize;j++)
            {
                if(ReadWriteDataFromFiles.artwork[j].getIdArtist() == thisid)
                {
                    totalphotos++;
                 if(ReadWriteDataFromFiles.artwork[j].getIdCustomer() > 0)
                   {
                        totalearnedmoney += ReadWriteDataFromFiles.artwork[j].getPrice();
                        totalboughtphoto++;  
                    }
                }
            }
            ////get style of arts of customer
                String arr[] = artist.getStyleOfArts();
                 String styleofart = "";
                for(int k = 0 ;k < artist.getnOfStyleOfArts(); k++)
                {
                    styleofart +=arr[k] + '-';       
                }
                
            
           tblmodel.addRow(new Object[]{
               (""+ thisid),artist.getName(),artist.getAge(),artist.getNationality(),
               artist.getnOfStyleOfArts(),styleofart,totalphotos,
               totalboughtphoto,totalearnedmoney});
                }
        }
        
    }
    
    private void set_gallary_data()
    {
        if(ReadWriteDataFromFiles.artworksize > 0)
        {
         photoplacejLabel2.setIcon(resizeImage(ReadWriteDataFromFiles.artwork[changephoto].getPath(), null,photoplacejLabel2));
         setidLabel9.setText("" + ReadWriteDataFromFiles.artwork[changephoto].getId());
         settitleLabel11.setText(ReadWriteDataFromFiles.artwork[changephoto].getTitle());
         setpriceLabel10.setText("" +ReadWriteDataFromFiles.artwork[changephoto].getPrice()); 
         seyearLabel12.setText("" +ReadWriteDataFromFiles.artwork[changephoto].getYear()); 
         setcategoryLabel13.setText(ReadWriteDataFromFiles.artwork[changephoto].getTypeOfArt());
         try
         {
             setartistmaderLabel15.setText(ReadWriteDataFromFiles.pearsons[ReadWriteDataFromFiles.artwork[changephoto].getIdArtist()-1].getName()); 
         }
         catch(Exception e)
         {
             setartistmaderLabel15.setText("Admin");
         }
         if(ReadWriteDataFromFiles.artwork[changephoto].getIdCustomer() == 0 )
             setcustomerboughtrLabel16.setText("Not Bought.");
         else
             setcustomerboughtrLabel16.setText(ReadWriteDataFromFiles.pearsons[ReadWriteDataFromFiles.artwork[changephoto].getIdCustomer()-1].getName()); 
       
         chngenuberlabel.setText((changephoto+1)+ "/" + ReadWriteDataFromFiles.artworksize);
        
        }
        else
        {
         photoplacejLabel2.setIcon(null);
         setidLabel9.setText("");
         settitleLabel11.setText("");
         setpriceLabel10.setText(""); 
         seyearLabel12.setText(""); 
         setcategoryLabel13.setText("");
         setartistmaderLabel15.setText(""); 
         setartistmaderLabel15.setText("");
         chngenuberlabel.setText("");
        }
        
    
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Choose_Photo_jButton3;
    private javax.swing.JPanel Head;
    private javax.swing.JButton Save__photo_jButton2;
    private javax.swing.JLabel addphotoid1;
    private javax.swing.JPanel addphototab3;
    private javax.swing.JTabbedPane adminbody;
    private javax.swing.JTable artisttbl;
    private javax.swing.JTextField categorytextfield1;
    private javax.swing.JLabel chngenuberlabel;
    private javax.swing.JLabel closeicon;
    private javax.swing.JTable customertbl;
    private javax.swing.JPanel datatblstab;
    private javax.swing.JPanel gallaytab;
    private javax.swing.JPanel hometab;
    private javax.swing.JLabel idjLabel10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel minminze;
    private javax.swing.JButton nextportfoliojButton1;
    private javax.swing.JLabel photoplacejLabel2;
    private javax.swing.JLabel photoplacelabel1;
    private javax.swing.JButton previousportfoliojButton2;
    private javax.swing.JTextField priceindollartextfield1;
    private javax.swing.JLabel setartistmaderLabel15;
    private javax.swing.JLabel setcategoryLabel13;
    private javax.swing.JLabel setcustomerboughtrLabel16;
    private javax.swing.JLabel setidLabel9;
    private javax.swing.JLabel setpriceLabel10;
    private javax.swing.JLabel settitleLabel11;
    private javax.swing.JLabel seyearLabel12;
    private javax.swing.JTextField titleofphototetxtfield1;
    private javax.swing.JLabel titlephotojLabel11;
    private javax.swing.JLabel totalartboughtphtotolabel3;
    private javax.swing.JLabel totalartboughtphtotolabel4;
    private javax.swing.JLabel totalartsitslabel;
    private javax.swing.JLabel totalartsitslabel1;
    private javax.swing.JLabel totalartworkslabel2;
    private javax.swing.JLabel totalartworkslabel3;
    private javax.swing.JLabel totalcustomersslabel1;
    private javax.swing.JLabel totalcustomersslabel2;
    private javax.swing.JLabel totalearnedmoneylabel4;
    private javax.swing.JLabel totalearnedmoneylabel5;
    private javax.swing.JLabel yearmadelabel3;
    private javax.swing.JLabel yearmadelabel4;
    private javax.swing.JLabel yearmadelabel5;
    private javax.swing.JTextField yearmadetextfield1;
    // End of variables declaration//GEN-END:variables
}
