/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ALLGUI;

import javax.swing.JFrame;
import ALLCLASS.*;
import static ALLCLASS.ReadWriteDataFromFiles.pearsons;
import java.awt.*;
import java.io.File;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author A7med_Sa3d
 */
public class ArtistPage extends javax.swing.JFrame {

    /**
     * Creates new form ArtistPage
     */
    
    private String addimagepath;
    private ARTWORK artistartwork[] = new ARTWORK[20];
    private int artworksize = 0;
    private int changephoto;
    
    public ArtistPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        changephoto = 0;
        
        getartistimage();
        
        setprofiledata();
        addphotoid.setText("" + (ReadWriteDataFromFiles.artworksize+1));
        if(artworksize > 0)
            set_portfolio_data();
        
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        minminze = new javax.swing.JLabel();
        closeicon = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        yourprofiletab1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        idlabel = new javax.swing.JLabel();
        setidlabel = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        setnamelabel1 = new javax.swing.JLabel();
        agelabel = new javax.swing.JLabel();
        setagelabel = new javax.swing.JLabel();
        setnationalitylabel = new javax.swing.JLabel();
        nationaliylabel = new javax.swing.JLabel();
        styleofartslabel = new javax.swing.JLabel();
        setstyleofartslabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        totalearnedmoneylabel = new javax.swing.JLabel();
        nofboughtphotolabel = new javax.swing.JLabel();
        tnofphotolabel = new javax.swing.JLabel();
        settotalearnedmoneylabel = new javax.swing.JLabel();
        settnofphotolabel = new javax.swing.JLabel();
        setnofboughtphotolabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addphototab2 = new javax.swing.JPanel();
        photoplacelabel = new javax.swing.JLabel();
        Choose_Photo_jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        idjLabel9 = new javax.swing.JLabel();
        addphotoid = new javax.swing.JLabel();
        titlephotojLabel10 = new javax.swing.JLabel();
        titleofphototetxtfield = new javax.swing.JTextField();
        yearmadelabel = new javax.swing.JLabel();
        yearmadetextfield = new javax.swing.JTextField();
        yearmadelabel1 = new javax.swing.JLabel();
        priceindollartextfield = new javax.swing.JTextField();
        yearmadelabel2 = new javax.swing.JLabel();
        categorytextfield = new javax.swing.JTextField();
        Save__photo_jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        porfoliotab3 = new javax.swing.JPanel();
        photoplacejLabel2 = new javax.swing.JLabel();
        chngenuberlabel = new javax.swing.JLabel();
        nextjButton1 = new javax.swing.JButton();
        previousjButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        setidLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        settitleLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        setpriceLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        seyearLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        setcategoryLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        setcustomerLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Head.setBackground(new java.awt.Color(255, 153, 169));

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ART GALLERY");

        minminze.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        minminze.setForeground(new java.awt.Color(255, 255, 255));
        minminze.setText("-");
        minminze.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minminze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minminzeMouseClicked(evt);
            }
        });

        closeicon.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        closeicon.setForeground(new java.awt.Color(255, 255, 255));
        closeicon.setText("X");
        closeicon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeiconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeadLayout = new javax.swing.GroupLayout(Head);
        Head.setLayout(HeadLayout);
        HeadLayout.setHorizontalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minminze)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeicon)
                .addGap(18, 18, 18))
        );
        HeadLayout.setVerticalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeadLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minminze)
                    .addComponent(closeicon))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jTabbedPane1.setInheritsPopupMenu(true);

        yourprofiletab1.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(240, 230, 220));
        jPanel1.setLayout(null);

        idlabel.setBackground(new java.awt.Color(204, 255, 51));
        idlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idlabel.setText("ID :");
        jPanel1.add(idlabel);
        idlabel.setBounds(30, 50, 34, 35);

        setidlabel.setBackground(new java.awt.Color(204, 255, 51));
        setidlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setidlabel.setText(" ");
        jPanel1.add(setidlabel);
        setidlabel.setBounds(90, 60, 63, 30);

        namelabel.setBackground(new java.awt.Color(204, 255, 51));
        namelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namelabel.setText("Name :");
        jPanel1.add(namelabel);
        namelabel.setBounds(20, 90, 57, 35);

        setnamelabel1.setBackground(new java.awt.Color(204, 255, 51));
        setnamelabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setnamelabel1.setText(" ");
        jPanel1.add(setnamelabel1);
        setnamelabel1.setBounds(100, 100, 63, 30);

        agelabel.setBackground(new java.awt.Color(204, 255, 51));
        agelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        agelabel.setText("Age :");
        jPanel1.add(agelabel);
        agelabel.setBounds(20, 130, 42, 35);

        setagelabel.setBackground(new java.awt.Color(204, 255, 51));
        setagelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setagelabel.setText(" ");
        jPanel1.add(setagelabel);
        setagelabel.setBounds(90, 130, 93, 30);

        setnationalitylabel.setBackground(new java.awt.Color(204, 255, 51));
        setnationalitylabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setnationalitylabel.setText(" ");
        jPanel1.add(setnationalitylabel);
        setnationalitylabel.setBounds(130, 170, 93, 30);

        nationaliylabel.setBackground(new java.awt.Color(204, 255, 51));
        nationaliylabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nationaliylabel.setText("Nationality : ");
        jPanel1.add(nationaliylabel);
        nationaliylabel.setBounds(20, 170, 101, 35);

        styleofartslabel.setBackground(new java.awt.Color(204, 255, 51));
        styleofartslabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        styleofartslabel.setText("Style of Art :");
        jPanel1.add(styleofartslabel);
        styleofartslabel.setBounds(20, 210, 101, 35);

        setstyleofartslabel.setBackground(new java.awt.Color(204, 255, 51));
        setstyleofartslabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setstyleofartslabel.setText(" ");
        jPanel1.add(setstyleofartslabel);
        setstyleofartslabel.setBounds(150, 220, 170, 22);

        jLabel10.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Personal Information");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 20, 220, 24);

        yourprofiletab1.add(jPanel1);
        jPanel1.setBounds(640, 20, 360, 260);

        jPanel2.setBackground(new java.awt.Color(240, 230, 220));
        jPanel2.setLayout(null);

        totalearnedmoneylabel.setBackground(new java.awt.Color(204, 255, 51));
        totalearnedmoneylabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalearnedmoneylabel.setText("Total Earned Money : ");
        jPanel2.add(totalearnedmoneylabel);
        totalearnedmoneylabel.setBounds(10, 50, 176, 35);

        nofboughtphotolabel.setBackground(new java.awt.Color(204, 255, 51));
        nofboughtphotolabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nofboughtphotolabel.setText("Number of Sold Photos :");
        jPanel2.add(nofboughtphotolabel);
        nofboughtphotolabel.setBounds(10, 90, 210, 35);

        tnofphotolabel.setBackground(new java.awt.Color(204, 255, 51));
        tnofphotolabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tnofphotolabel.setText("Total no. of photos : ");
        jPanel2.add(tnofphotolabel);
        tnofphotolabel.setBounds(10, 130, 180, 35);

        settotalearnedmoneylabel.setBackground(new java.awt.Color(204, 255, 51));
        settotalearnedmoneylabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        settotalearnedmoneylabel.setText(" ");
        jPanel2.add(settotalearnedmoneylabel);
        settotalearnedmoneylabel.setBounds(200, 50, 80, 30);

        settnofphotolabel.setBackground(new java.awt.Color(204, 255, 51));
        settnofphotolabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        settnofphotolabel.setText(" ");
        jPanel2.add(settnofphotolabel);
        settnofphotolabel.setBounds(200, 130, 80, 30);

        setnofboughtphotolabel1.setBackground(new java.awt.Color(204, 255, 51));
        setnofboughtphotolabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setnofboughtphotolabel1.setText(" ");
        jPanel2.add(setnofboughtphotolabel1);
        setnofboughtphotolabel1.setBounds(220, 90, 80, 30);

        jLabel11.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Photos Information");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(80, 20, 200, 24);

        yourprofiletab1.add(jPanel2);
        jPanel2.setBounds(640, 310, 360, 180);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/girl-2696947_960_720PHOTORESIZERCROPRESIZEANDSHAREIMAGESINBATCH56201944512AM.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        yourprofiletab1.add(jLabel9);
        jLabel9.setBounds(30, 10, 540, 500);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background-2579710_1280.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        yourprofiletab1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1020, 520);

        jTabbedPane1.addTab("Your Profile", yourprofiletab1);

        addphototab2.setLayout(null);

        photoplacelabel.setBackground(new java.awt.Color(255, 102, 102));
        addphototab2.add(photoplacelabel);
        photoplacelabel.setBounds(580, 30, 400, 337);

        Choose_Photo_jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Choose_Photo_jButton2.setText("Choose Photo");
        Choose_Photo_jButton2.setIconTextGap(10);
        Choose_Photo_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Choose_Photo_jButton2ActionPerformed(evt);
            }
        });
        addphototab2.add(Choose_Photo_jButton2);
        Choose_Photo_jButton2.setBounds(680, 390, 233, 40);

        jPanel3.setBackground(new java.awt.Color(240, 230, 220));

        idjLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idjLabel9.setText("Id :");

        addphotoid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        titlephotojLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titlephotojLabel10.setText("Title :");

        yearmadelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yearmadelabel.setText("Year : ");

        yearmadetextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearmadetextfieldKeyTyped(evt);
            }
        });

        yearmadelabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yearmadelabel1.setText("Price :");

        priceindollartextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceindollartextfieldKeyTyped(evt);
            }
        });

        yearmadelabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yearmadelabel2.setText("Category :");

        Save__photo_jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Save__photo_jButton1.setText("Save");
        Save__photo_jButton1.setIconTextGap(10);
        Save__photo_jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Save__photo_jButton1MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Photo Information");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Save__photo_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idjLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearmadelabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearmadelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearmadelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titlephotojLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleofphototetxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearmadetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceindollartextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categorytextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addphotoid, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idjLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addphotoid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlephotojLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleofphototetxtfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearmadelabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(yearmadetextfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearmadelabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(priceindollartextfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearmadelabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(categorytextfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(Save__photo_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        addphototab2.add(jPanel3);
        jPanel3.setBounds(12, 54, 336, 358);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background-2579710_1280.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        addphototab2.add(jLabel12);
        jLabel12.setBounds(0, 0, 1020, 520);

        jTabbedPane1.addTab("Add Photo", addphototab2);

        porfoliotab3.setLayout(null);
        porfoliotab3.add(photoplacejLabel2);
        photoplacejLabel2.setBounds(479, 77, 529, 283);
        porfoliotab3.add(chngenuberlabel);
        chngenuberlabel.setBounds(479, 433, 59, 25);

        nextjButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nextjButton1.setText("Next");
        nextjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextjButton1ActionPerformed(evt);
            }
        });
        porfoliotab3.add(nextjButton1);
        nextjButton1.setBounds(908, 433, 90, 25);

        previousjButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        previousjButton2.setText("Previous");
        previousjButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousjButton2MouseClicked(evt);
            }
        });
        porfoliotab3.add(previousjButton2);
        previousjButton2.setBounds(12, 433, 100, 25);

        jPanel4.setBackground(new java.awt.Color(240, 230, 220));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Id :");

        setidLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Title :");

        settitleLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Price :");

        setpriceLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Year :");

        seyearLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Category : ");

        setcategoryLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Customer Bought : ");

        setcustomerLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Photo Information");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(setidLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(setcustomerLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(setcategoryLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(seyearLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(setpriceLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(settitleLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setidLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settitleLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setpriceLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seyearLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setcategoryLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setcustomerLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        porfoliotab3.add(jPanel4);
        jPanel4.setBounds(21, 50, 320, 376);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background-2579710_1280.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        porfoliotab3.add(jLabel14);
        jLabel14.setBounds(0, 0, 1020, 520);

        jTabbedPane1.addTab("Portfolio", porfoliotab3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     private Boolean check_add_photo_data()
    {
        if(titleofphototetxtfield.getText().equals("") || yearmadetextfield.getText().equals("") ||priceindollartextfield.getText().equals("") ||categorytextfield.getText().equals("") ||photoplacelabel.getIcon() == null )
        {
           JOptionPane.showMessageDialog(this,"Empty Fields.","Message", JOptionPane.WARNING_MESSAGE);
            return false; 
        }
        
      return true;
    }
    
    private Boolean check_add_photo_name(String newname)
    {
        for(int i = 0 ;i<ReadWriteDataFromFiles.artworksize ; i++)
            if(ReadWriteDataFromFiles.artwork[i].getTitle().equals(newname))
            {
                JOptionPane.showMessageDialog(this,"this is name is used before.","Message", JOptionPane.ERROR_MESSAGE);
                return false;
            }
    return true;
    }
     
     private void getartistimage()
    {
        for(int i = 0 ;i < ReadWriteDataFromFiles.artworksize ; i++)
        {
            if(ReadWriteDataFromFiles.artwork[i].getIdArtist() == LOGINFORM.SignInid)
            {
                artistartwork[artworksize] = ReadWriteDataFromFiles.artwork[i];
                artworksize++;
            }
        }
    }
    
    private ImageIcon resizeImage(String imagepath , byte[] pic,JLabel x)
    {
        ImageIcon myimg = null;
        if(imagepath !=null)
            myimg = new ImageIcon(imagepath);
        else
            myimg = new ImageIcon(pic);
        Image img = myimg.getImage();
        Image img2 = img.getScaledInstance(x.getWidth(),x.getHeight(),Image.SCALE_SMOOTH);
        
        ImageIcon imageicon = new ImageIcon(img2);
        
    return imageicon;
    }
    
    
    private void minminzeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minminzeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minminzeMouseClicked

    private void closeiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeiconMouseClicked
        //System.exit(0);
        this.dispose();
        new LOGINFORM().setVisible(true);
    }//GEN-LAST:event_closeiconMouseClicked

    private void Save__photo_jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Save__photo_jButton1MouseClicked

        if(check_add_photo_data() && check_add_photo_name(titleofphototetxtfield.getText()) )
        {
            ARTWORK newartwork = new ARTWORK();
            newartwork.setId(ReadWriteDataFromFiles.artworksize+1);
            newartwork.setTitle(titleofphototetxtfield.getText());
            newartwork.setIdArtist(LOGINFORM.SignInid);
            newartwork.setIdCustomer(0);//not bought yet
            
            newartwork.setYear(Integer.parseInt(yearmadetextfield.getText()));
            newartwork.setPrice(Integer.parseInt(priceindollartextfield.getText()));
            newartwork.setTypeOfArt(categorytextfield.getText());
            newartwork.setPath(addimagepath);
            
            JOptionPane.showMessageDialog(this,"Data Saved Sir.","Message", JOptionPane.OK_OPTION);
            
            ReadWriteDataFromFiles.addNewartwork(newartwork);
            
            addphotoid.setText("" + (ReadWriteDataFromFiles.artworksize+1));
            titleofphototetxtfield.setText("");
            yearmadetextfield.setText("");
            priceindollartextfield.setText("");
            categorytextfield.setText("");
            addimagepath = "";
            photoplacelabel.setIcon(null);
            
            //add this new photo to the portfolio
            artistartwork[artworksize] = newartwork;
            artworksize++;
            set_portfolio_data();
            setprofiledata();
        }

    }//GEN-LAST:event_Save__photo_jButton1MouseClicked

    private void Choose_Photo_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choose_Photo_jButton2ActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images","jpg","png");
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File selectedfile = file.getSelectedFile();
            addimagepath = selectedfile.getAbsolutePath();
            photoplacelabel.setIcon(resizeImage(addimagepath, null,photoplacelabel));
        }
        else
        {
            JOptionPane.showMessageDialog(this,"No File Chooser","Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Choose_Photo_jButton2ActionPerformed

    private void nextjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextjButton1ActionPerformed
        // TODO add your handling code here:
        if(artworksize > 0)
        {
            changephoto++;
            if(changephoto == artworksize )
            changephoto = 0;
            set_portfolio_data();
        }
        else
        JOptionPane.showMessageDialog(this,"You havn't any photo.","Message", JOptionPane.WARNING_MESSAGE);

        
        
    }//GEN-LAST:event_nextjButton1ActionPerformed

    private void previousjButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousjButton2MouseClicked
        // TODO add your handling code here:
        if(artworksize > 0)
        {
            changephoto--;
            if(changephoto == -1 )
            changephoto = artworksize - 1;
            set_portfolio_data();
        }
        else
        JOptionPane.showMessageDialog(this,"You havn't any photo.","Message", JOptionPane.WARNING_MESSAGE);
    
        
    }//GEN-LAST:event_previousjButton2MouseClicked

    private void yearmadetextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearmadetextfieldKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_yearmadetextfieldKeyTyped

    private void priceindollartextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceindollartextfieldKeyTyped
        // TODO add your handling code here:
         if(!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_priceindollartextfieldKeyTyped

    private void setprofiledata()
    {
         int getid = LOGINFORM.SignInid - 1;
        
         ARTIST artist = new ARTIST();
                artist = (ARTIST) ReadWriteDataFromFiles.pearsons[getid].get_data();
        
        setidlabel.setText("" + artist.getId());
        setnamelabel1.setText(artist.getName());
        setagelabel.setText("" + artist.getAge());
        setnationalitylabel.setText(artist.getNationality());
        String arr[] = artist.getStyleOfArts();
        String styleofart = "";
        for(int i = 0 ;i < artist.getnOfStyleOfArts(); i++)
        {
               styleofart +=arr[i] + '-';       
        }
        setstyleofartslabel.setText(styleofart);
        
        int totalearnedmoney = 0 , totalboughtphotos = 0;
        for(int i = 0 ;i < artworksize ;i++)
            if(artistartwork[i].getIdCustomer() > 0 )
            {
                totalearnedmoney += artistartwork[i].getPrice();
                totalboughtphotos++;
            }
        settotalearnedmoneylabel.setText("" + totalearnedmoney + " $");
        setnofboughtphotolabel1.setText("" + totalboughtphotos);
        settnofphotolabel.setText("" + artworksize);
    }
    
    private void set_portfolio_data()
    {
         photoplacejLabel2.setIcon(resizeImage(artistartwork[changephoto].getPath(), null,photoplacejLabel2));
         setidLabel9.setText("" + artistartwork[changephoto].getId());
         settitleLabel11.setText(artistartwork[changephoto].getTitle());
         setpriceLabel10.setText("" +artistartwork[changephoto].getPrice()); 
         seyearLabel12.setText("" +artistartwork[changephoto].getYear()); 
         setcategoryLabel13.setText(artistartwork[changephoto].getTypeOfArt());
         
         if(artistartwork[changephoto].getIdCustomer()> 0 )
         setcustomerLabel14.setText(ReadWriteDataFromFiles.pearsons[artistartwork[changephoto].getIdCustomer() - 1].getName()); 
         else
             setcustomerLabel14.setText("NOt Bought Yet");
         chngenuberlabel.setText((changephoto +1)+ "/" + artworksize);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArtistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArtistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArtistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArtistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArtistPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Choose_Photo_jButton2;
    private javax.swing.JPanel Head;
    private javax.swing.JButton Save__photo_jButton1;
    private javax.swing.JLabel addphotoid;
    private javax.swing.JPanel addphototab2;
    private javax.swing.JLabel agelabel;
    private javax.swing.JTextField categorytextfield;
    private javax.swing.JLabel chngenuberlabel;
    private javax.swing.JLabel closeicon;
    private javax.swing.JLabel idjLabel9;
    private javax.swing.JLabel idlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel minminze;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel nationaliylabel;
    private javax.swing.JButton nextjButton1;
    private javax.swing.JLabel nofboughtphotolabel;
    private javax.swing.JLabel photoplacejLabel2;
    private javax.swing.JLabel photoplacelabel;
    private javax.swing.JPanel porfoliotab3;
    private javax.swing.JButton previousjButton2;
    private javax.swing.JTextField priceindollartextfield;
    private javax.swing.JLabel setagelabel;
    private javax.swing.JLabel setcategoryLabel13;
    private javax.swing.JLabel setcustomerLabel14;
    private javax.swing.JLabel setidLabel9;
    private javax.swing.JLabel setidlabel;
    private javax.swing.JLabel setnamelabel1;
    private javax.swing.JLabel setnationalitylabel;
    private javax.swing.JLabel setnofboughtphotolabel1;
    private javax.swing.JLabel setpriceLabel10;
    private javax.swing.JLabel setstyleofartslabel;
    private javax.swing.JLabel settitleLabel11;
    private javax.swing.JLabel settnofphotolabel;
    private javax.swing.JLabel settotalearnedmoneylabel;
    private javax.swing.JLabel seyearLabel12;
    private javax.swing.JLabel styleofartslabel;
    private javax.swing.JTextField titleofphototetxtfield;
    private javax.swing.JLabel titlephotojLabel10;
    private javax.swing.JLabel tnofphotolabel;
    private javax.swing.JLabel totalearnedmoneylabel;
    private javax.swing.JLabel yearmadelabel;
    private javax.swing.JLabel yearmadelabel1;
    private javax.swing.JLabel yearmadelabel2;
    private javax.swing.JTextField yearmadetextfield;
    private javax.swing.JPanel yourprofiletab1;
    // End of variables declaration//GEN-END:variables
}
