/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ALLGUI;

import ALLCLASS.*;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author A7med_Sa3d
 */
public class CustomerPage extends javax.swing.JFrame {

    /**
     * Creates new form CustomerPage
     */
    
    private String addimagepath;
    private ARTWORK customerartwork[];
    private int customerartworksize = 0;
    private ARTWORK avaliableartwork[];
    private int avaliableartworksize = 0;
    
    private int changephotoinportfolio;
    private int changephotoinbuyphoto;
    private Boolean ava_search ;       
    private int totalearnedmoney = 0 ;

    
    
    public CustomerPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        customerartwork = new ARTWORK[50];
        avaliableartwork = new ARTWORK[50];
        
        get_customer_img();
        setprofiledata();
        
        avaliableartwork = get_avaliable_img();
       setbuyphotodata();
       set_portfolio_data();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        minminze = new javax.swing.JLabel();
        closeicon = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        yourprofiletab1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        idlabel = new javax.swing.JLabel();
        setidlabel = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        setnamelabel1 = new javax.swing.JLabel();
        nationaliylabel = new javax.swing.JLabel();
        setaddresslabel = new javax.swing.JLabel();
        totalearnedmoneylabel = new javax.swing.JLabel();
        settotalearnedmoneylabel = new javax.swing.JLabel();
        nofboughtphotolabel = new javax.swing.JLabel();
        setnofboughtphotolabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        porfoliotab4 = new javax.swing.JPanel();
        photoplacejLabel3 = new javax.swing.JLabel();
        chngenuberlabel1 = new javax.swing.JLabel();
        nextbuyphotojButton2 = new javax.swing.JButton();
        previousbuyphotojButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        seachbytextfiled = new javax.swing.JTextField();
        cancelsearchjButton1 = new javax.swing.JButton();
        BuyphotoBtn = new javax.swing.JButton();
        searchjButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        setidLabel10 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        settitleLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        setpriceLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        seyearLabel13 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        setcategoryLabel14 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        setartistmadeLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        porfoliotab3 = new javax.swing.JPanel();
        photoplacejLabel2 = new javax.swing.JLabel();
        chngenuberlabel = new javax.swing.JLabel();
        nextportfoliojButton1 = new javax.swing.JButton();
        previousportfoliojButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        setidLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        settitleLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        setpriceLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        seyearLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        setcategoryLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        setartistmaderLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Head.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ART GALLERY");

        minminze.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        minminze.setForeground(new java.awt.Color(255, 255, 255));
        minminze.setText("-");
        minminze.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minminze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minminzeMouseClicked(evt);
            }
        });

        closeicon.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        closeicon.setForeground(new java.awt.Color(255, 255, 255));
        closeicon.setText("X");
        closeicon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeiconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeadLayout = new javax.swing.GroupLayout(Head);
        Head.setLayout(HeadLayout);
        HeadLayout.setHorizontalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadLayout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addComponent(minminze)
                .addGap(18, 18, 18)
                .addComponent(closeicon)
                .addContainerGap())
        );
        HeadLayout.setVerticalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeadLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minminze)
                    .addComponent(closeicon))
                .addGap(24, 24, 24))
        );

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        yourprofiletab1.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 225, 225));

        idlabel.setBackground(new java.awt.Color(204, 255, 51));
        idlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idlabel.setText("ID :");

        setidlabel.setBackground(new java.awt.Color(204, 255, 51));
        setidlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setidlabel.setText(" ");

        namelabel.setBackground(new java.awt.Color(204, 255, 51));
        namelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namelabel.setText("Name :");

        setnamelabel1.setBackground(new java.awt.Color(204, 255, 51));
        setnamelabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setnamelabel1.setText(" ");

        nationaliylabel.setBackground(new java.awt.Color(204, 255, 51));
        nationaliylabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nationaliylabel.setText("Address :");

        setaddresslabel.setBackground(new java.awt.Color(204, 255, 51));
        setaddresslabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setaddresslabel.setText(" ");

        totalearnedmoneylabel.setBackground(new java.awt.Color(204, 255, 51));
        totalearnedmoneylabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalearnedmoneylabel.setText("Total Money : ");

        settotalearnedmoneylabel.setBackground(new java.awt.Color(204, 255, 51));
        settotalearnedmoneylabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        settotalearnedmoneylabel.setText(" ");

        nofboughtphotolabel.setBackground(new java.awt.Color(204, 255, 51));
        nofboughtphotolabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nofboughtphotolabel.setText("Nof Bought photo : ");

        setnofboughtphotolabel1.setBackground(new java.awt.Color(204, 255, 51));
        setnofboughtphotolabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setnofboughtphotolabel1.setText(" ");

        jLabel15.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Personal Information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(totalearnedmoneylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(settotalearnedmoneylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nationaliylabel)
                                    .addComponent(namelabel)
                                    .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(setnamelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(setaddresslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(setidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(nofboughtphotolabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(setnofboughtphotolabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setnamelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nationaliylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setaddresslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalearnedmoneylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settotalearnedmoneylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nofboughtphotolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setnofboughtphotolabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        yourprofiletab1.add(jPanel1);
        jPanel1.setBounds(880, 90, 360, 380);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/man-2781994_1280PHOTORESIZERCROPRESIZEANDSHAREIMAGESINBATCH56201965216AM.jpg"))); // NOI18N
        jLabel17.setText("jLabel17");
        yourprofiletab1.add(jLabel17);
        jLabel17.setBounds(30, 20, 770, 500);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hardwood-1851071_1280.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        yourprofiletab1.add(jLabel16);
        jLabel16.setBounds(0, 0, 1280, 570);

        jTabbedPane1.addTab("Your Profile", yourprofiletab1);

        porfoliotab4.setLayout(null);
        porfoliotab4.add(photoplacejLabel3);
        photoplacejLabel3.setBounds(650, 100, 480, 280);
        porfoliotab4.add(chngenuberlabel1);
        chngenuberlabel1.setBounds(890, 400, 59, 25);

        nextbuyphotojButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nextbuyphotojButton2.setText("Next");
        nextbuyphotojButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbuyphotojButton2ActionPerformed(evt);
            }
        });
        porfoliotab4.add(nextbuyphotojButton2);
        nextbuyphotojButton2.setBounds(1020, 400, 110, 25);

        previousbuyphotojButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        previousbuyphotojButton3.setText("Previous");
        previousbuyphotojButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousbuyphotojButton3MouseClicked(evt);
            }
        });
        porfoliotab4.add(previousbuyphotojButton3);
        previousbuyphotojButton3.setBounds(720, 400, 110, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Search :");
        porfoliotab4.add(jLabel2);
        jLabel2.setBounds(490, 30, 107, 30);
        porfoliotab4.add(seachbytextfiled);
        seachbytextfiled.setBounds(600, 30, 220, 22);

        cancelsearchjButton1.setText("Cancel");
        cancelsearchjButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelsearchjButton1MouseClicked(evt);
            }
        });
        porfoliotab4.add(cancelsearchjButton1);
        cancelsearchjButton1.setBounds(990, 30, 101, 25);

        BuyphotoBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BuyphotoBtn.setText("BUY");
        BuyphotoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuyphotoBtnMouseClicked(evt);
            }
        });
        porfoliotab4.add(BuyphotoBtn);
        BuyphotoBtn.setBounds(480, 481, 210, 40);

        searchjButton3.setText("Search");
        searchjButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchjButton3MouseClicked(evt);
            }
        });
        porfoliotab4.add(searchjButton3);
        searchjButton3.setBounds(850, 30, 101, 25);

        jPanel2.setBackground(new java.awt.Color(204, 225, 225));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Id :");

        setidLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Title :");

        settitleLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Price :");

        setpriceLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Year :");

        seyearLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Category : ");

        setcategoryLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Artist : ");

        setartistmadeLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Photo Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(setidLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(settitleLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(seyearLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(setpriceLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(setartistmadeLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(setcategoryLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(setidLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settitleLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setpriceLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seyearLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setcategoryLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setartistmadeLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        porfoliotab4.add(jPanel2);
        jPanel2.setBounds(20, 80, 320, 370);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hardwood-1851071_1280.jpg"))); // NOI18N
        jLabel19.setText("jLabel19");
        porfoliotab4.add(jLabel19);
        jLabel19.setBounds(0, 0, 1280, 550);

        jTabbedPane1.addTab("Buy Photo", porfoliotab4);

        porfoliotab3.setLayout(null);
        porfoliotab3.add(photoplacejLabel2);
        photoplacejLabel2.setBounds(667, 67, 526, 283);
        porfoliotab3.add(chngenuberlabel);
        chngenuberlabel.setBounds(939, 439, 59, 25);

        nextportfoliojButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nextportfoliojButton1.setText("Next");
        nextportfoliojButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextportfoliojButton1ActionPerformed(evt);
            }
        });
        porfoliotab3.add(nextportfoliojButton1);
        nextportfoliojButton1.setBounds(1081, 439, 100, 25);

        previousportfoliojButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        previousportfoliojButton2.setText("Previous");
        previousportfoliojButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousportfoliojButton2MouseClicked(evt);
            }
        });
        porfoliotab3.add(previousportfoliojButton2);
        previousportfoliojButton2.setBounds(753, 439, 100, 25);

        jPanel3.setBackground(new java.awt.Color(204, 225, 225));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Id :");

        setidLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Title :");

        settitleLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Price :");

        setpriceLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Year :");

        seyearLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Category : ");

        setcategoryLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Artist : ");

        setartistmaderLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Photo Information");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(settitleLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(seyearLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(setpriceLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(setcategoryLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(setartistmaderLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(setidLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel20)
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setidLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(settitleLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setpriceLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seyearLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setcategoryLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(setartistmaderLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        porfoliotab3.add(jPanel3);
        jPanel3.setBounds(46, 45, 325, 419);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hardwood-1851071_1280.jpg"))); // NOI18N
        jLabel21.setText("jLabel21");
        porfoliotab3.add(jLabel21);
        jLabel21.setBounds(0, 0, 1280, 560);

        jTabbedPane1.addTab("Portfolio", porfoliotab3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ImageIcon resizeImage(String imagepath , byte[] pic,JLabel x)
    {
        ImageIcon myimg = null;
        if(imagepath !=null)
            myimg = new ImageIcon(imagepath);
        else
            myimg = new ImageIcon(pic);
        Image img = myimg.getImage();
        Image img2 = img.getScaledInstance(x.getWidth(),x.getHeight(),Image.SCALE_SMOOTH);
        
        ImageIcon imageicon = new ImageIcon(img2);
        
    return imageicon;
    }
    
    private ARTWORK[] get_avaliable_img()
    {
          ARTWORK avawork[] = new ARTWORK[50];
           avaliableartworksize = 0;   
        for(int i = 0 ;i < ReadWriteDataFromFiles.artworksize ; i++)
        {
            if(ReadWriteDataFromFiles.artwork[i].getIdCustomer()== 0)
            {
                avawork[avaliableartworksize] = ReadWriteDataFromFiles.artwork[i];
                avaliableartworksize++;
            }
        }
        return avawork;
    }
    private ARTWORK[] get_avalible_search_img(String category_search)
    {
           ARTWORK avawork[] = new ARTWORK[50];
           int c = 0;   
           ava_search = false;
        for(int i = 0 ;i < ReadWriteDataFromFiles.artworksize ; i++)
        {
            if(category_search.equals(ReadWriteDataFromFiles.artwork[i].getTypeOfArt()) && ReadWriteDataFromFiles.artwork[i].getIdCustomer()== 0)
            {
                avawork[c] = ReadWriteDataFromFiles.artwork[i];
                ava_search = true;
                c++;
            }
        }
        if(c > 0)
            avaliableartworksize = c;
        return avawork;
    }
    
    private void get_customer_img()
    {
        customerartworksize = 0;
        for(int i = 0 ;i < ReadWriteDataFromFiles.artworksize ; i++)
        {
            if(ReadWriteDataFromFiles.artwork[i].getIdCustomer() == LOGINFORM.SignInid )
            {
                customerartwork[customerartworksize] = ReadWriteDataFromFiles.artwork[i];
                customerartworksize++;
            }
        }
    }
    
    private void set_portfolio_data()
    {
        if(customerartworksize > 0)
        {
         photoplacejLabel2.setIcon(resizeImage(customerartwork[changephotoinportfolio].getPath(), null,photoplacejLabel2));
         setidLabel9.setText("" + customerartwork[changephotoinportfolio].getId());
         settitleLabel11.setText(customerartwork[changephotoinportfolio].getTitle());
         setpriceLabel10.setText("" +customerartwork[changephotoinportfolio].getPrice()); 
         seyearLabel12.setText("" +customerartwork[changephotoinportfolio].getYear()); 
         setcategoryLabel13.setText(customerartwork[changephotoinportfolio].getTypeOfArt());
         try
         {
             setartistmaderLabel14.setText(ReadWriteDataFromFiles.pearsons[customerartwork[changephotoinportfolio].getIdArtist()-1].getName()); 
         }
         catch(Exception e)
         {
             setartistmaderLabel14.setText("Admin");
         }
         chngenuberlabel.setText((changephotoinportfolio +1)+ "/" + customerartworksize);
        }
        else
        {
         photoplacejLabel2.setIcon(null);
         setidLabel9.setText("");
         settitleLabel11.setText("");
         setpriceLabel10.setText(""); 
         seyearLabel12.setText(""); 
         setcategoryLabel13.setText("");
         setartistmaderLabel14.setText(""); 
         chngenuberlabel.setText("");
        }
    }
    
    private void setprofiledata()
    {
         int getid = LOGINFORM.SignInid- 1;
        CUSTOMER customer = new CUSTOMER();
                 customer = (CUSTOMER) ReadWriteDataFromFiles.pearsons[getid].get_data();
                    
        setidlabel.setText("" + customer.getId());
        
        setnamelabel1.setText(customer.getName());
        setaddresslabel.setText(customer.getAddress());
         
        for(int i = 0 ;i < customerartworksize ;i++)
                totalearnedmoney += customerartwork[i].getPrice();
            
        settotalearnedmoneylabel.setText("" + totalearnedmoney + " $");
        setnofboughtphotolabel1.setText("" + customerartworksize);
       
    }
    
    private void setbuyphotodata()
    {
        if(avaliableartworksize > 0)
        {
         try
         {
            
         photoplacejLabel3.setIcon(resizeImage(avaliableartwork[changephotoinbuyphoto].getPath(), null,photoplacejLabel3));
         setidLabel10.setText("" + avaliableartwork[changephotoinbuyphoto].getId());
         settitleLabel12.setText(avaliableartwork[changephotoinbuyphoto].getTitle());
         setpriceLabel11.setText("" +avaliableartwork[changephotoinbuyphoto].getPrice()); 
         seyearLabel13.setText("" +avaliableartwork[changephotoinbuyphoto].getYear()); 
         setcategoryLabel14.setText(avaliableartwork[changephotoinbuyphoto].getTypeOfArt());
         try{
            setartistmadeLabel15.setText(ReadWriteDataFromFiles.pearsons[avaliableartwork[changephotoinbuyphoto].getIdArtist()-1].getName()); 
         }
         catch(Exception e)
         {
             setartistmadeLabel15.setText("Admin");
         }
         
         chngenuberlabel1.setText((changephotoinbuyphoto +1)+ "/" + avaliableartworksize);
         }
         catch(Exception ee){}
         
         
         }
    else
        {
         photoplacejLabel3.setIcon(null);
         setidLabel10.setText("");
         settitleLabel12.setText("");
         setpriceLabel11.setText(""); 
         seyearLabel13.setText(""); 
         setcategoryLabel14.setText("");
         setartistmadeLabel15.setText(""); 
         chngenuberlabel1.setText("");
        }
    
    }
    
    
    private void minminzeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minminzeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minminzeMouseClicked

    private void closeiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeiconMouseClicked
        //System.exit(0);
        this.dispose();
        new LOGINFORM().setVisible(true);
    }//GEN-LAST:event_closeiconMouseClicked

    private void nextportfoliojButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextportfoliojButton1ActionPerformed
        // TODO add your handling code here:
        if(customerartworksize > 0)
        {
            changephotoinportfolio++;
            if(changephotoinportfolio == customerartworksize )
                changephotoinportfolio = 0;
            set_portfolio_data();
        }
        else
             JOptionPane.showMessageDialog(this,"You havn't any photo.","Message", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_nextportfoliojButton1ActionPerformed

    private void previousportfoliojButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousportfoliojButton2MouseClicked
        // TODO add your handling code here:
        if(customerartworksize > 0)
        {
            changephotoinportfolio--;
            if(changephotoinportfolio == -1 )
                changephotoinportfolio = customerartworksize - 1;
            set_portfolio_data();
        }
        else
          JOptionPane.showMessageDialog(this,"You havn't any photo.","Message", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_previousportfoliojButton2MouseClicked

    private void nextbuyphotojButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbuyphotojButton2ActionPerformed
        // TODO add your handling code here:
        if(avaliableartworksize > 0)
        {
            changephotoinbuyphoto++;
            if(changephotoinbuyphoto == avaliableartworksize )
                changephotoinbuyphoto = 0;
            setbuyphotodata();
        }
        else
             JOptionPane.showMessageDialog(this,"System havn't any photo.","Message", JOptionPane.WARNING_MESSAGE);

        
    }//GEN-LAST:event_nextbuyphotojButton2ActionPerformed

    private void previousbuyphotojButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousbuyphotojButton3MouseClicked
        // TODO add your handling code here:
        if(avaliableartworksize > 0)
        {
            changephotoinbuyphoto--;
            if(changephotoinbuyphoto == -1 )
                changephotoinbuyphoto = avaliableartworksize - 1;
            setbuyphotodata();        
        }
        else
             JOptionPane.showMessageDialog(this,"System havn't any photo.","Message", JOptionPane.WARNING_MESSAGE);

        
    }//GEN-LAST:event_previousbuyphotojButton3MouseClicked

    private void searchjButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchjButton3MouseClicked
        // TODO add your handling code here:
        String searchtext = seachbytextfiled.getText();
        ARTWORK temp[] = new ARTWORK[50];
        
        temp = get_avalible_search_img(searchtext);
        
        if(ava_search)
        {
          JOptionPane.showMessageDialog(this,"Search Done.","Message", JOptionPane.INFORMATION_MESSAGE);
          avaliableartwork = temp;
          setbuyphotodata();
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Can't Find this category.","Message", JOptionPane.WARNING_MESSAGE);
                        setbuyphotodata();    
        
        }
    
    }//GEN-LAST:event_searchjButton3MouseClicked

    private void cancelsearchjButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelsearchjButton1MouseClicked
        // TODO add your handling code here:
       seachbytextfiled.setText("");
       avaliableartwork = get_avaliable_img();
             setbuyphotodata();
       ava_search = false;
    }//GEN-LAST:event_cancelsearchjButton1MouseClicked

    private void BuyphotoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuyphotoBtnMouseClicked
        // TODO add your handling code here:
      if(avaliableartworksize > 0){
       int buyid = Integer.parseInt(setidLabel10.getText());
       ReadWriteDataFromFiles.artwork[buyid - 1].setIdCustomer(LOGINFORM.SignInid);
       ReadWriteDataFromFiles.WriteDataIntoArtWork();
       JOptionPane.showMessageDialog(this,"Buy Done.","Message", JOptionPane.INFORMATION_MESSAGE);
       
       get_customer_img();
        
       set_portfolio_data();
       setprofiledata();
       
       avaliableartwork = get_avaliable_img();
       seachbytextfiled.setText("");
       changephotoinbuyphoto = 0;
       setbuyphotodata();
      }
        else
             JOptionPane.showMessageDialog(this,"System havn't any photo.","Message", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_BuyphotoBtnMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuyphotoBtn;
    private javax.swing.JPanel Head;
    private javax.swing.JButton cancelsearchjButton1;
    private javax.swing.JLabel chngenuberlabel;
    private javax.swing.JLabel chngenuberlabel1;
    private javax.swing.JLabel closeicon;
    private javax.swing.JLabel idlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel minminze;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel nationaliylabel;
    private javax.swing.JButton nextbuyphotojButton2;
    private javax.swing.JButton nextportfoliojButton1;
    private javax.swing.JLabel nofboughtphotolabel;
    private javax.swing.JLabel photoplacejLabel2;
    private javax.swing.JLabel photoplacejLabel3;
    private javax.swing.JPanel porfoliotab3;
    private javax.swing.JPanel porfoliotab4;
    private javax.swing.JButton previousbuyphotojButton3;
    private javax.swing.JButton previousportfoliojButton2;
    private javax.swing.JTextField seachbytextfiled;
    private javax.swing.JButton searchjButton3;
    private javax.swing.JLabel setaddresslabel;
    private javax.swing.JLabel setartistmadeLabel15;
    private javax.swing.JLabel setartistmaderLabel14;
    private javax.swing.JLabel setcategoryLabel13;
    private javax.swing.JLabel setcategoryLabel14;
    private javax.swing.JLabel setidLabel10;
    private javax.swing.JLabel setidLabel9;
    private javax.swing.JLabel setidlabel;
    private javax.swing.JLabel setnamelabel1;
    private javax.swing.JLabel setnofboughtphotolabel1;
    private javax.swing.JLabel setpriceLabel10;
    private javax.swing.JLabel setpriceLabel11;
    private javax.swing.JLabel settitleLabel11;
    private javax.swing.JLabel settitleLabel12;
    private javax.swing.JLabel settotalearnedmoneylabel;
    private javax.swing.JLabel seyearLabel12;
    private javax.swing.JLabel seyearLabel13;
    private javax.swing.JLabel totalearnedmoneylabel;
    private javax.swing.JPanel yourprofiletab1;
    // End of variables declaration//GEN-END:variables
}
