/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ALLGUI;

import ALLCLASS.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author A7med_Sa3d
 */
public class LOGINFORM extends javax.swing.JFrame {

    /**
     * Creates new form LOGINFORM
     */
    //start varibles
    public static int SignInid;
    private String username;
    private String password;
    //end variables
    
    
    public LOGINFORM() {
        initComponents();
        this.setLocationRelativeTo(null);//center the form
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LOGINHEADERBAR = new javax.swing.JPanel();
        LOGINHEADER = new javax.swing.JLabel();
        CloseBtn = new javax.swing.JLabel();
        MinimizeBtn = new javax.swing.JLabel();
        LOGINBODY = new javax.swing.JPanel();
        COPYWRIGHT = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        usernamelablel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordlabel = new javax.swing.JLabel();
        passwordField2 = new javax.swing.JPasswordField();
        showpasswordCheckBox = new javax.swing.JCheckBox();
        loginbutton = new javax.swing.JButton();
        NewclientButton = new javax.swing.JButton();
        newartistbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        LOGINHEADERBAR.setBackground(new java.awt.Color(87, 96, 111));

        LOGINHEADER.setFont(new java.awt.Font("Algerian", 3, 40)); // NOI18N
        LOGINHEADER.setForeground(new java.awt.Color(255, 255, 255));
        LOGINHEADER.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGINHEADER.setText("ART GALLERY");

        CloseBtn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        CloseBtn.setForeground(new java.awt.Color(255, 255, 255));
        CloseBtn.setText("X");
        CloseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBtnMouseClicked(evt);
            }
        });

        MinimizeBtn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        MinimizeBtn.setForeground(new java.awt.Color(255, 255, 255));
        MinimizeBtn.setText("-");
        MinimizeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LOGINHEADERBARLayout = new javax.swing.GroupLayout(LOGINHEADERBAR);
        LOGINHEADERBAR.setLayout(LOGINHEADERBARLayout);
        LOGINHEADERBARLayout.setHorizontalGroup(
            LOGINHEADERBARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGINHEADERBARLayout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(LOGINHEADER, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329)
                .addComponent(MinimizeBtn)
                .addGap(18, 18, 18)
                .addComponent(CloseBtn)
                .addGap(18, 18, 18))
        );
        LOGINHEADERBARLayout.setVerticalGroup(
            LOGINHEADERBARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGINHEADERBARLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LOGINHEADERBARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(LOGINHEADERBARLayout.createSequentialGroup()
                        .addComponent(CloseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addGroup(LOGINHEADERBARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MinimizeBtn)
                        .addComponent(LOGINHEADER)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LOGINBODY.setBackground(new java.awt.Color(47, 53, 66));
        LOGINBODY.setLayout(null);

        COPYWRIGHT.setBackground(new java.awt.Color(47, 53, 66));
        COPYWRIGHT.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        COPYWRIGHT.setForeground(new java.awt.Color(255, 255, 255));
        COPYWRIGHT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        COPYWRIGHT.setText("Copyright © 2019 By Error Team");
        LOGINBODY.add(COPYWRIGHT);
        COPYWRIGHT.setBounds(510, 520, 220, 16);

        usernamelablel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        usernamelablel.setForeground(new java.awt.Color(51, 51, 51));
        usernamelablel.setText("Username :");

        usernameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        passwordlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passwordlabel.setForeground(new java.awt.Color(51, 51, 51));
        passwordlabel.setText("Password :");

        passwordField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        showpasswordCheckBox.setBackground(new java.awt.Color(216, 216, 236));
        showpasswordCheckBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        showpasswordCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        showpasswordCheckBox.setText("showPassword");
        showpasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordCheckBoxActionPerformed(evt);
            }
        });

        loginbutton.setBackground(new java.awt.Color(204, 204, 204));
        loginbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        NewclientButton.setBackground(new java.awt.Color(243, 172, 172));
        NewclientButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NewclientButton.setText("New Client");
        NewclientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewclientButtonActionPerformed(evt);
            }
        });

        newartistbutton.setBackground(new java.awt.Color(243, 172, 172));
        newartistbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newartistbutton.setText("New Artist");
        newartistbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newartistbuttonMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login Form");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-icon.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User-Interface-Password-2-icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(passwordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showpasswordCheckBox)
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(usernamelablel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(234, 234, 234))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(NewclientButton)
                        .addGap(105, 105, 105)
                        .addComponent(newartistbutton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(usernamelablel)
                                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordlabel)
                            .addComponent(passwordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showpasswordCheckBox)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(loginbutton)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewclientButton)
                    .addComponent(newartistbutton))
                .addGap(24, 24, 24))
        );

        LOGINBODY.add(jPanel1);
        jPanel1.setBounds(770, 80, 440, 320);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/WhatsApp Image 2019-04-20 at 2.02.54 PM.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        LOGINBODY.add(jLabel2);
        jLabel2.setBounds(0, 0, 1250, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LOGINHEADERBAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LOGINBODY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(LOGINBODY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(LOGINHEADERBAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 520, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String checkdata()
    {
        
        if(username.equals("admin") && password.equals("123456"))
        {
               return "admin";
        }
        for(int i=0 ; i<ReadWriteDataFromFiles.pearsonssize ; i++)
        
            if(ReadWriteDataFromFiles.pearsons[i].getName().equals(username) &&ReadWriteDataFromFiles.pearsons[i].getPassword().equals(password))
            {
                ///fe one add here to use in array sub 1 from signinid//
                LOGINFORM.SignInid = i+1;
                if(ReadWriteDataFromFiles.pearsons[i] instanceof CUSTOMER )
                     return "customer";
                else if(ReadWriteDataFromFiles.pearsons[i] instanceof ARTIST )
                return "artist";
            }
        return "fail";
    }
    
    private void CloseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBtnMouseClicked

    private void MinimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeBtnMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeBtnMouseClicked

    private void showpasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordCheckBoxActionPerformed
        if(showpasswordCheckBox.isSelected())
        passwordField2.setEchoChar((char)0);
        else {
            passwordField2.setEchoChar('*');
        }

    }//GEN-LAST:event_showpasswordCheckBoxActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed

        username = usernameTextField.getText();
        password = passwordField2.getText();
       switch (checkdata())
        {
            case "artist":
                new ArtistPage().setVisible(true);
                this.dispose();
                break;

            case "customer":
                new CustomerPage().setVisible(true);
                this.dispose();
                break;

            case "admin" :
                new AdminPage().setVisible(true);
                this.dispose();
                break;
            
            case "fail":
                JOptionPane.showMessageDialog(LOGINBODY,"Invalid Username or Password","Welcome", JOptionPane.ERROR_MESSAGE);
                break;
                default:
                break;
        }
        //JOptionPane.showMessageDialog(this,"fail Login.","YaWelcome", JOptionPane.ERROR_MESSAGE);
           
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void NewclientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewclientButtonActionPerformed
        AddNewCustomerForm newcustomerform = new AddNewCustomerForm();
        newcustomerform.setVisible(true);
        newcustomerform.pack();
        newcustomerform.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_NewclientButtonActionPerformed

    private void newartistbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newartistbuttonMouseClicked
        AddNewArtistFrom newcustomerform = new AddNewArtistFrom();
        newcustomerform.setVisible(true);
        newcustomerform.pack();
        newcustomerform.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_newartistbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGINFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGINFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGINFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGINFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGINFORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel COPYWRIGHT;
    private javax.swing.JLabel CloseBtn;
    private javax.swing.JPanel LOGINBODY;
    private javax.swing.JLabel LOGINHEADER;
    private javax.swing.JPanel LOGINHEADERBAR;
    private javax.swing.JLabel MinimizeBtn;
    private javax.swing.JButton NewclientButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbutton;
    private javax.swing.JButton newartistbutton;
    private javax.swing.JPasswordField passwordField2;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JCheckBox showpasswordCheckBox;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JLabel usernamelablel;
    // End of variables declaration//GEN-END:variables
}
